# Generated by Django 4.2.3 on 2023-07-20 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_department'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Department',
        ),
    ]
