# Generated by Django 4.2.3 on 2023-07-23 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='Issue_Brief',
            new_name='sym_des',
        ),
    ]
