# Generated by Django 4.2.3 on 2023-07-23 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0002_rename_issue_brief_patient_sym_des'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='shift',
        ),
    ]
